<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Asura.Kubernetes.Tests" />
    <ProjectReference Include="../Asura.Application/Asura.Application.csproj" />
    <PackageReference Include="KubernetesClient.Aot" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
